export const SCENES_COUNT = 4
export const SCENE_PADDING = 50
export const SCROLL_HEIGHT = (100 * SCENES_COUNT) + (SCENE_PADDING * (SCENES_COUNT - 1))

export const VENUE_LATITUDE = 37.5062334
export const VENUE_LONGITUDE = 127.0670974

export const SCENE_FOUR_DIM_PADDING = (SCENE_PADDING * 3)
